In [165]:
import numpy as np
import cv2

img = cv2.imread('02.png')
#print(img.shape)

#------------------------
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# lower mask (0-10)
lower_red = np.array([10,50,50])
upper_red = np.array([170,255,255])
mask0 = cv2.inRange(img_hsv, lower_red, upper_red)

# upper mask (170-180)
lower_red = np.array([180,50,50])
upper_red = np.array([255,255,255])
mask1 = cv2.inRange(img_hsv, lower_red, upper_red)

# join my masks
mask = mask0+mask1
# set my output img to zero everywhere except my mask
output_img = img.copy()
output_img[np.where(mask==0)] = 0

# or your HSV image, which I *believe* is what you want
output_hsv = img_hsv.copy()
output_hsv[np.where(mask==0)] = 0
#------------------------
cv2.imshow('Image', output_hsv)
cv2.waitKey(0)
cv2.destroyAllWindows()

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(gray,127,255,1)
contours,h = cv2.findContours(thresh,1,2)
print(len(contours))

39


In [138]:
import numpy as np
import cv2
img = cv2.imread('02.png',cv2.IMREAD_UNCHANGED)
print(img.shape)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(gray,127,255,1)
contours,h = cv2.findContours(thresh,1,2)
print(len(contours))

cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

(382, 791, 4)
39


In [124]:
for cnt in contours:
    approx = cv2.approxPolyDP(cnt,0.01*cv2.arcLength(cnt,True),True)
    if len(approx)==4:
        print("square",cnt[0],cnt[1],cnt[2],cnt[3])
        #cv2.drawContours(img,[cnt],0,(0,0,255),-1)
    elif len(approx)==3:
        print("Triangle",cnt[0])
        #cv2.drawContours(img,[cnt],0,(0,0,255),-1)
    elif len(approx)==6:
        print("Hexagon",cnt[0])
        #cv2.drawContours(img,[cnt],0,(0,0,255),-1)
    elif len(approx)==8:
        print("Octagon",cnt[0])
        cv2.drawContours(img,[cnt],0,(0,0,255),-1)
    elif len(approx)==10:
        print("Ten",cnt[0])
        cv2.drawContours(img,[cnt],0,(0,0,255),-1)

Ten [[311 247]]
Ten [[314 240]]
Octagon [[561  99]]
Ten [[551  99]]
Octagon [[117  90]]
Octagon [[100  90]]
Octagon [[78 90]]
Hexagon [[62 90]]
Ten [[119  87]]
square [[111  87]] [[111  96]] [[112  96]] [[112  87]]
square [[72 87]] [[72 96]] [[73 96]] [[73 87]]
square [[68 87]] [[68 96]] [[69 96]] [[69 87]]
Triangle [[198  75]]
Triangle [[195  68]]
Hexagon [[549  55]]
square [[44 53]] [[45 52]] [[138  52]] [[139  53]]
Hexagon [[550  50]]
square [[40 48]] [[ 40 150]] [[143 150]] [[143  48]]


In [126]:
cv2.imshow('Image', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [111]:
for cnt in contours:
    approx = cv2.approxPolyDP(cnt,0.01*cv2.arcLength(cnt,True),True)
    if len(approx)==4:
        print("square",cnt)
        #cv2.drawContours(img,[cnt],0,(0,0,255),-1)

square [[[ 44  53]]

 [[ 45  52]]

 [[138  52]]

 [[139  53]]

 [[139 145]]

 [[138 146]]

 [[ 45 146]]

 [[ 44 145]]]
square [[[ 40  48]]

 [[ 40 150]]

 [[143 150]]

 [[143  48]]]


In [145]:
height,width, _=img.shape

(382, 791, 3)
9


In [169]:
import numpy as np
import cv2
img = cv2.imread('01.png')
print(img.shape)
#----------------
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
ret,thresh = cv2.threshold(gray, 240, 255, cv2.THRESH_BINARY)
contours,h = cv2.findContours(thresh,1,2)
print(len(contours))

for cnt in contours:
    approx = cv2.approxPolyDP(cnt,0.01*cv2.arcLength(cnt,True),True)
    if len(approx)==4:
        print("square",cnt[0],cnt[1],cnt[2],cnt[3])
        #cv2.drawContours(img,[cnt],0,(0,0,255),-1)
    elif len(approx)==3:
        print("Triangle",cnt[0])
        #cv2.drawContours(img,[cnt],0,(0,0,255),-1)
    elif len(approx)==6:
        print("Hexagon",cnt[0])
        #cv2.drawContours(img,[cnt],0,(0,0,255),-1)
    elif len(approx)==8:
        print("Octagon",cnt[0])
        cv2.drawContours(img,[cnt],0,(0,0,255),-1)
    elif len(approx)==10:
        print("Ten",cnt[0])
        cv2.drawContours(img,[cnt],0,(0,0,255),-1)

Ten [[312 247]]
Ten [[314 239]]
Triangle [[199  75]]
Triangle [[195  67]]
Hexagon [[550  55]]
square [[45 53]] [[ 45 145]] [[138 145]] [[138  53]]
Hexagon [[549  50]]
square [[39 48]] [[40 47]] [[143  47]] [[144  48]]
square [[0 0]] [[  0 381]] [[790 381]] [[790   0]]
